import type { Metadata } from "next";
import "./globals.css";
import Modal from "@/components/Modal";



export const metadata: Metadata = {
  title: "Trello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        {children}
        <Modal />
      </body>
    </html>
  );
}
